# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore HvalfangstApi/HvalfangstApi.csproj
      
    - name: Build
      run: dotnet build HvalfangstApi/HvalfangstApi.csproj --no-restore
      
    - name: Run Tests with Coverage
      run: |
        dotnet test HvalfangstTests/HvalfangstTests.csproj \
        --collect:"XPlat Code Coverage" \
        --results-directory ./TestResults \
        --logger "trx;LogFileName=test_results.trx"

    - name: List TestResults Directory
      run: ls -R ./TestResults

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Generate Coverage Report
      run: |
        reportgenerator \
        -reports:./TestResults/**/coverage.cobertura.xml \
        -targetdir:./CoverageReport \
        -reporttypes:TextSummary

    - name: Display Coverage Report
      run: cat ./CoverageReport/Summary.txt